### ISSUE TITLE
バスレイアウト

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/HakodateBusApp#1]
<img width="356" alt="スクリーンショット 2021-10-19 0 54 25" src="https://user-images.githubusercontent.com/62680416/137766296-25c25b52-d70a-4aae-b84f-c6e45ebc9d7f.png">
<img width="356" alt="スクリーンショット 2021-10-19 0 54 45" src="https://user-images.githubusercontent.com/62680416/137766379-09d69c63-58b5-4e5a-921c-3ff15f2b9207.png">
<img width="354" alt="スクリーンショット 2021-10-19 0 55 26" src="https://user-images.githubusercontent.com/62680416/137766479-e24e54c5-6157-4937-9015-db317ccfc0aa.png">

**Comment by Fuyan777** [comment]
デザイン変更したらアップデートしてね👍
