### ISSUE TITLE
日報

### ISSUE THREAD

**Issue by sasakisyota** [sasakisyota/HakodateBusApp#2]
# 10/18(月)

## やったこと（時間）
- バスアプリレイアウト作成(オートリサイジング、オートレイアウト)（1h）

## 次やること
UI部品の配置、ビュー、シーンの作成

## 困っていること
どのような手順で他の人はアプリの画面を作成しているのか気になる

**Comment by sasakisyota** [comment]
# 10/19(火)

## やったこと（時間）
- ボタンの設定（1h）

## 次やること
UI部品の配置、シーンの作成

## 困っていること
特になし。認知心理学のレポートがあるので早く終わらせて続きをやりたいです...

**Comment by sasakisyota** [comment]
# 10/22(金)~10/23(土)

## やったこと（時間）
- タブバーでの画面遷移(2h)
- マップの導入(4h)

## 次やること
UI部品の配置

## 困っていること
マップの上にどのように画面を表示させるか方法を調べる。記事が古いと今のxcodeと対応しているツールがどれなのかわからないことが多い。

**Comment by sasakisyota** [comment]
# 10/24(日)

## やったこと（時間）
- UI部分の配置(2h)


## 次やること
UI部品の配置の続き

## 困っていること
UIの設定を苦戦している。

**Comment by sasakisyota** [comment]
# 10/25(月)~10/26(火)

## やったこと（時間）
- UI部分の配置(3h)
- スタックビューについて調査(0.5h)


## 次やること
スタックビューの配置

## 困っていること
スタックビューの設定

**Comment by Fuyan777** [comment]
日報続けれてる？？

**Comment by sasakisyota** [comment]
ここ最近UIの事であまり進んでいなくて、進捗がなかったので出来ていなかったです。今日から気持ちを切り替えてまた日報書いていきます！

**Comment by sasakisyota** [comment]
# 11/7(日)

## やったこと（時間）
- レイアウトの最後の調整(2h)

## 次やること
ハコスペースのUI作成

## 困っていること
バスのレイアウトが完成出来なくて残念です...

**Comment by sasakisyota** [comment]
# 11/8(月)

## やったこと（時間）
- navigationControllerの作成(0.5h)

<img width="612" alt="スクリーンショット 2021-11-09 1 50 17" src="https://user-images.githubusercontent.com/62680416/140784875-3ad8869e-ff5d-4bac-8007-925a2384a26c.png">
- 質問の仕方の記事(0.5h)

## 次やること
tableViewCell、tableViewでUI作成

## 困っていること
疑問点をしっかりと言語化して質問力を上げていきたいです

**Comment by sasakisyota** [comment]
# 11/9(火)

## やったこと（時間）
-TabelViewでレイアウト作成(2.5h)


## 次やること
tableViewCell、tableViewでUI作成の続き

## 困っていること
<img width="1107" alt="スクリーンショット 2021-11-10 0 48 16" src="https://user-images.githubusercontent.com/62680416/140957151-7f125d1e-9ea9-4922-a4e1-240d00173012.png">

https://i-app-tec.com/ios/tableview.html
この記事を読んでimgArrayをアイコンの名前に変更し、Tag番号も設定したのですがUIImageViewインスタンスの作成のimageViewとlabel1.textとlabel2.textを変更してどうにか自分で設定したセルのimageとlabelと紐づけたいのですがやり方が調べてもいまいち分からなかった。まだUITableViewDataSource, UITableViewDelegate、dequeueReusableCellがよく分からないので明日はhttps://softmoco.com/basics/how-to-use-table-view.php　
この記事を参考にしながらもう一度やってみます。

**Comment by Fuyan777** [comment]
@sasakisyota 

コメント3点！

1点目
現状、何ができていて、何ができていないというのを明確に記述してもらえると、相手に伝わりやすいと思う！

> Tag番号も設定したのですがUIImageViewインスタンスの作成のimageViewとlabel1.textとlabel2.textを変更してどうにか自分で設定したセルのimageとlabelと紐づけたいのですがやり方が調べてもいまいち分からなかった。

これは、何をしたい？そして、何が問題で実装できていない？
storyboardで設定したラベルとコードの変更を紐付けたいということ？

2点目
直接storyboardでセルを作成してしまうと、セルが何個も増えてきたときに対応できないので、
セルはxibファイルで作成してもらうと良いかな！

3点目
できれば、GitHubのリポジトリにあげてもらいたい！
詰まった時こちらがコード確認できるので、原因特定しやすい

**Comment by sasakisyota** [comment]
# 11/10(水)

## やったこと（時間）
- 作業記録のレイアウトのやること作成(1h)


## 次やること
やることに従ってレイアウトの作成

## 困っていること
自分で色々調べながらやっていると途中で何を今しているのか、何をやりたいのかが分からなくなる。
もう少し検索能力を上げて言語化していきたい

**Comment by sasakisyota** [comment]
# 11/11(木)

## やったこと（時間）
- セルを作成し、テーブルに表示させた(2h)


## 次やること
gitHubにpushするファイルを間違えていたっぽいのでもう一度やり直す。
画像を表示できるように作る

## 困っていること
セルに画像とラベルをどのように配列から取り出して表示させれば良いか分からない

**Comment by sasakisyota** [comment]
https://yuu.1000quu.com/use_a_custom_cell_in_swift
https://satoriku.com/customcell/

**Comment by sasakisyota** [comment]
# 11/12(金)

## やったこと（時間）
- カスタムセルの設定(2h)


## 次やること
画像を表示できるように作る

## 困っていること
特になし

**Comment by sasakisyota** [comment]
# 11/13(土)

## やったこと（時間）
- カスタムセルの設定(1h)


## 次やること
カスタムセルの続き

## 困っていること
特になし

**Comment by sasakisyota** [comment]
# 11/14(日)

## やったこと（時間）
- カスタムセルの設定(3h)


## 次やること
storyboardからコードにリファクタリング

## 困っていること
アプリの見積もりをやったことが無かったのでちゃんとできているのか分からなかった。
